# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_origin: ['https://localhost:5173']
#         # allow_origin: ['*']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization', 'Content-Disposition']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/': ~

# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_origin: ['http://localhost:5173']
#         # allow_origin: ['*']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization', 'Content-Disposition']
#         expose_headers: ['Link']
#         max_age: 3600
#         hosts: []
#         origin_regex: false
#         forced_allow_origin_value: ~
#         skip_same_as_origin: true
#     paths:
#         '^/api/':
#             allow_origin: ['*']
#             allow_headers: ['X-Custom-Auth']
#             allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#             max_age: 3600
#         '^/':
#             origin_regex: true
#             allow_origin: ['^http://localhost:[0-9]+']
#             allow_headers: ['X-Custom-Auth']
#             allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#             max_age: 3600
#             hosts: ['^api\.']

nelmio_cors:
  defaults:
    origin_regex: true
    allow_credentials: true
    allow_origin: ["http://localhost:5173"]
    allow_methods: ["GET", "OPTIONS", "PUT", "PATCH", "DELETE", "POST"]
    allow_headers: ["Content-Type", "Authorization", "Cookie"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/":
      allow_methods: ["OPTIONS", "PUT", "POST", "GET", "PATCH", "DELETE"]
# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['http://localhost:5173']
#         allow_methods: []

#  'https://70bd-2a01-e0a-849-4580-30a9-f4a2-18c9-6c6e.ngrok-free.app', 'https://checkout.stripe.com/'

# nelmio_cors:
#     defaults:
#         allow_credentials: false
#         allow_origin: []
#         allow_headers: []
#         allow_methods: []
#         expose_headers: []
#         max_age: 0
#         hosts: []
#         origin_regex: false
#         forced_allow_origin_value: ~
#         skip_same_as_origin: true
#     paths:
#         '^/api/':
#             allow_origin: ['*']
#             allow_headers: ['X-Custom-Auth']
#             allow_methods: ['POST', 'PUT', 'DELETE']
#             max_age: 3600
#         '^/':
#             origin_regex: true
#             allow_origin: ['^http://localhost:[0-9]+']
#             allow_headers: ['X-Custom-Auth']
#             allow_methods: ['POST', 'PUT', 'DELETE']
#             max_age: 3600
#             hosts: ['^api\.']
